vim.g.mapleader = ' '
require('configs')
require('plugins')
require('keymaps')
require('completion')
require('lsp')
require('ai')
require('format')
require('statusline')
require('session')
require('git')
require('terminal')
require('whichkey')
require('autosave')

